- hosts: web
  become: True
  vars_files:
    - vars.yml
  tasks:
    - name: Install apache
      dnf:
        name: httpd
        state: present
      tags:
        - install
    - name: create index.html on apache server
      copy:
        src: index.html
        dest: /var/www/html/
      tags:
        - deploy
    - name: start and enable apache
      service:
        name: httpd
        state: started
        enabled: True
    - name: change default port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen"
        insertafter: '^#Listen '
        line: "Listen {{default_port}}"
      notify:
        - restart apache
      tags:
        - configure
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
