- hosts: web[0]
  tasks:
    - name: Check if app is healthy
      uri:
        url: "http://54.227.176.227/"
        return_content: true
      register: info
    - name: Run this task if app is healthy
      debug:
        msg: "App is healthy"
      when: info.status == 200

